version: ${project.version}

database:
  #存储类型 SQLite、Mysql、Yaml
  type: yaml
  #以下参数为mysql配置
  mysql_ip: 127.0.0.1
  mysql_port: 3306
  mysql_username: root
  mysql_password: 123456
  mysql_database: "ctonlinetime"
  mysql_option: "useUnicode=true&characterEncoding=utf-8&useSSL=false"
  hikariCP:
    #数据库连接池配置，基本无需改动，如需改动请根据自身需要修改，谨慎修改可能会造成插件无法使用
    connectionTimeout: 30000
    #连接超时时间 默认值：30000（30秒）
    minimumIdle: 10
    #最小空闲连接数
    maximumPoolSize: 50
    #池允许达到的最大大小，包括空闲和正在使用的连接
Setting:
  #菜单中物品默认材质
  defaultItemType:
    type:
      name: 'GLASS_BOTTLE'
      #是否打开附魔  部分物品会出现问题，请提前测试
      enchantment: false

