name: CtOnlineReward
version: ${project.version}
main: cn.ctcraft.ctonlinereward.CtOnlineReward
softdepend: [PlaceholderAPI,PlayerPoints,Vault]
commands:
  cor:
    description: CtOnlineReward Main Command
api-version: 1.13